### ISSUE TITLE
Exception when connecting to an unreachable local host.

### ISSUE THREAD

**Issue by clarketm** [clarketm/wait-for-it#25]
```console
wait-for-it -s localhost:1234
```
```
[*] Waiting 15 seconds for localhost:1234
Traceback (most recent call last):
  File "/usr/local/bin/wait-for-it", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wait_for_it/wait_for_it.py", line 98, in cli
    _connect_all_serial(service, timeout)
  File "/usr/local/lib/python3.8/site-packages/wait_for_it/wait_for_it.py", line 183, in _connect_all_serial
    connect(service, timeout)
  File "/usr/local/lib/python3.8/site-packages/wait_for_it/wait_for_it.py", line 191, in connect
    _asyncio_run(_wait_until_available_and_report(reporter, host, port))
  File "/usr/local/lib/python3.8/site-packages/wait_for_it/wait_for_it.py", line 24, in _asyncio_run
    return asyncio.run(*args, **kvargs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/wait_for_it/wait_for_it.py", line 51, in _wait_until_available_and_report
    await _wait_until_available(host, port)
  File "/usr/local/lib/python3.8/site-packages/wait_for_it/wait_for_it.py", line 39, in _wait_until_available
    _reader, writer = await asyncio.open_connection(host, port)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1033, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('127.0.0.1', 1234), [Errno 61] Connect call failed ('::1', 1234, 0, 0)
```

**Comment by hartwork** [comment]
Could this be specific to macOS? I don't see this behaviour on Linux.

**Comment by hartwork** [comment]
I found now that it's not specific to macOS but to IPv6. On your host, both IPv4 and IPv6 are tried for `localhost`. On the host I tested with, there is no IPv6 so it was IPv4 only and that passed. Interesting.

**Comment by hartwork** [comment]
It seems that IPv6 *alone* works fine:
```
$ wait-for-it -s [::1]:1234
[*] Waiting 15 seconds for ::1:1234
[-] Timeout occurred after waiting 15 seconds for ::1:1234
```

**Comment by clarketm** [comment]
> Could this be specific to macOS? I don't see this behaviour on Linux.

There must have been something strange going on locally because now I cannot reproduce. 🤷 . I will reopen if the issue resurfaces.

**Comment by clarketm** [comment]
> Could this be specific to macOS? I don't see this behaviour on Linux.

I am able to reproduce both on MacOS and Linux (CentOS)
